#!/usr/bin/env python
# -*- coding: UTF-8 -*-

"""
Use of freegeoip.net:

GET:
https://freegeoip.net/json/8.8.8.8

JSON:
{"ip":"8.8.8.8","country_code":"US","country_name":"Estados Unidos","region_code":"CA","region_name":"California","city":"Mountain View","zip_code":"94040","time_zone":"America/Los_Angeles","latitude":37.386,"longitude":-122.084,"metro_code":807}
"""

import json
import urllib2
import sys
import socket 

URL = 'https://freegeoip.net/json/'

def get_country(ip):
    try:
        response = urllib2.urlopen(URL+ip)
        data = json.load(response)
        return data["country_code"]

    except urllib2.HTTPError:
        return False

def validate_ip(ip):
    try:
        socket.inet_aton(ip)
        ip = True
    except socket.error:
        ip = False

    return ip

def get_argv():
    try:
        arg = sys.argv[1]
        return arg
    except:
        pass   


if __name__ == '__main__':

    IP = get_argv()

    if IP:
        if validate_ip(IP):
            country = get_country(IP)

            if country:
                print country
            else:
                print "ERROR: We can't get Country Code."
        else:
            print 'Invalid IP address... :('

    else:
        print ""
        print "Use:"
        print "\tgeoiplook IP"
        print "Example:"
        print "\tgeoiplook 8.8.8.8"
        print ""
       
